sudo: false
language: node_js
node_js:
  - v6
  - v5
  - v4
before_install:
  - npm install -g bower
install:
  - npm install
  - bower install
before_script:
# Special config for Chrome on Travis-CI
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
